[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
auto_detect_solc = false

# Test configuration
[profile.default.fuzz]
runs = 256

# RPC endpoints for different networks
[rpc_endpoints]
morph_holesky_testnet = "https://rpc-holesky.morphl2.io"
local = "http://localhost:8545"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
